---
global:
  pattern: travelops
  singleArgoCD: true

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
    autoApproveManualInstallPlans: true

main:
  variant: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
