{{- if not .Values.tempostack.minio.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.tempostack.storage.secretName }}
  namespace: {{ .Values.tempostack.namespace | default .Release.Namespace | quote }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.tempostack.storage.secretName }}
    template:
      type: Opaque
      data:
        bucket: {{ .Values.tempostack.storage.bucket | quote }}
        endpoint: {{ .Values.tempostack.storage.endpoint | quote }}
        access_key_id: "{{ `{{ .access_key_id }}` }}"
        access_key_secret: "{{ `{{ .access_key_secret }}` }}"
  data:
    - secretKey: access_key_id
      remoteRef:
        key: {{ .Values.secretStore.remoteKey }}
        property: {{ .Values.secretStore.accessKeyProperty }}
    - secretKey: access_key_secret
      remoteRef:
        key: {{ .Values.secretStore.remoteKey }}
        property: {{ .Values.secretStore.secretKeyProperty }}
{{- end }}
