name: Ansible Lint # feel free to pick your own name

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@8ba9595a4acd1b906eb75568b34f6ef592cd1528 # v26.3.0
        # Let's point it to the path
        with:
          working_directory: "ansible/"
